version: "3.8"
services:
  trigger:
    volumes:
      # Change ./path_to_local_ai_images_folder to point to the folder that
      # will have the images to analyze
      - ./path_to_local_ai_images_folder:/aiinput
      # Leave this unchanged, required for temporary data file storage
      - localtriggerstorage:/node-deepstackai-trigger

    environment:
      # Change this to match the timezone the images are produced in,
      # Typically this will be the timezone of the machine running
      # the Docker container. For a list of valid timezone values
      # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
      # The value to use is in the "TZ database name" column.
      - TZ=America/Los_Angeles
      # Modify this to change the default port used for the service that returns
      # annotated images. If you change this you also have to set the same value
      # in the ports: section below.
      - PORT=4242
      # This is pre-configured for service-to-service connectivity in
      # Docker. Don't change this unless there is a need to talk to an
      # external DeepStack server somewhere and you know what you are doing.
      - DEEPSTACK_URI=http://deepstack-ai:5000/

    ports:
      - 4242:4242

    secrets:
      - triggers
      # To enable MQTT uncomment the following line and add the server
      # connection settings to mqtt.json
      # - mqtt
      # To enable Telegram uncomment the following line and add the bot
      # token to telegram.json
      # - telegram

    # ------------------------------------------------------------------------
    # Don't change anything below this line unless you know what you are doing
    image: danecreekphotography/node-deepstackai-trigger:latest
    restart: always
    depends_on:
      - deepstack-ai

  deepstack-ai:
    image: deepquestai/deepstack:latest
    restart: always
    volumes:
      - localstorage:/datastore
    environment:
      - VISION-DETECTION=True

volumes:
  localstorage:
  localtriggerstorage:

secrets:
  triggers:
    # This should point to the location of the triggers.json configuration file
    file: ./triggers.json
  mqtt:
    # This should point to the location of the mqtt.json configuration file
    file: ./mqtt.json
  telegram:
    # This should point to the location of the telegram.json configuration file
    file: ./telegram.json
